export const PAGE_REDIRECTS_REQUEST_CONFIG = 'PAGE_REDIRECTS_REQUEST_CONFIG';
export const PAGE_REDIRECTS_RECEIVE_CONFIG = 'PAGE_REDIRECTS_RECEIVE_CONFIG';
export const PAGE_REDIRECTS_ERROR_CONFIG = 'PAGE_REDIRECTS_ERROR_CONFIG';
